version: '3.8'  # ← добавь версию

services:
  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_DB: fastapi_app
      POSTGRES_USER: fastuser
      POSTGRES_PASSWORD: fastpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - fastapi-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fastapi-net

volumes:
  pg_data:

networks:
  fastapi-net:
    driver: bridge